apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: europe-west2-docker.pkg.dev/inm420-cloud-ecommerce/ecommerce/react-app:latest
        ports:
        - containerPort: 3000